const en = {
	breakdown: "Snapshot breakdown",
	metricView: "Metric",
	tokens: "Tokens",
	snapshotOnly: "Current snapshot totals; this is not a historical trend.",
	title: "Assistant operations",
	description: "Availability, public knowledge and execution health.",
	status: "Service",
	knowledge: "Knowledge",
	usage: "Estimated usage",
	executions: "Executions",
	traces: "Technical traces",
	refresh: "Refresh data",
	preferences: "Preferences",
	language: "Language",
	theme: "Theme",
	dark: "Dark",
	light: "Light",
	access: "Manage access",
	signOut: "Sign out",
	total: "Total",
	completed: "Completed",
	cancelled: "Cancelled",
	failed: "Failed",
	firstToken: "First token · p95",
	notAvailable: "No data",
	reserve: "Reserved",
	budget: "Monthly limit",
	input: "Input tokens",
	output: "Output tokens",
	pricing:
		"Estimated from configured prices, not an OpenAI invoice. Unsettled reservations remain separate.",
	pendingTitle: "Operational integration is not configured",
	pendingBody:
		"The API owner must publish the operational contract before real metrics can appear here. No demo values are substituted.",
	unavailableTitle: "Operational data is unavailable",
	unavailableBody:
		"The data source could not be read safely. Refresh to try again; this does not generate an answer.",
	checked: "Checked",
	observed: "Source updated",
	source: "Indexed portfolio revision",
	corpus: "Corpus",
	indexed: "Indexed",
	emptyTraces:
		"No sampled traces in this snapshot. This does not mean that no requests occurred.",
	fixture: "Synthetic fixture data · not production telemetry",
	stages: "Stages",
	duration: "Duration",
	outcome: "Outcome",
	ready: "Ready",
	degraded: "Degraded",
	unavailable: "Unavailable",
	fresh: "Fresh",
	updating: "Updating",
	stale: "Stale",
	languageStage: "Language",
	vector_retrieval: "Vector retrieval",
	graph_retrieval: "Graph retrieval",
	generation: "Generation",
	finalization: "Finalization",
};
const es: { [Key in keyof typeof en]: string } = {
	breakdown: "Detalle de la consulta",
	metricView: "Métrica",
	tokens: "Tokens",
	snapshotOnly:
		"Totales de la consulta actual; no representan una tendencia histórica.",
	title: "Operaciones del asistente",
	description:
		"Disponibilidad, conocimiento público y estado de las ejecuciones.",
	status: "Servicio",
	knowledge: "Conocimiento",
	usage: "Consumo estimado",
	executions: "Ejecuciones",
	traces: "Trazas técnicas",
	refresh: "Actualizar datos",
	preferences: "Preferencias",
	language: "Idioma",
	theme: "Tema",
	dark: "Oscuro",
	light: "Claro",
	access: "Administrar acceso",
	signOut: "Cerrar sesión",
	total: "Total",
	completed: "Completadas",
	cancelled: "Canceladas",
	failed: "Fallidas",
	firstToken: "Primer token · p95",
	notAvailable: "Sin datos",
	reserve: "Reservado",
	budget: "Límite mensual",
	input: "Tokens de entrada",
	output: "Tokens de salida",
	pricing:
		"Estimación según los precios configurados, no una factura de OpenAI. Las reservas pendientes se muestran por separado.",
	pendingTitle: "La integración operativa no está configurada",
	pendingBody:
		"El responsable de la API debe publicar el contrato operativo para mostrar métricas reales. No se sustituyen con valores de demostración.",
	unavailableTitle: "Los datos operativos no están disponibles",
	unavailableBody:
		"No se pudo consultar la fuente de forma segura. Actualiza para volver a intentar; esto no genera una respuesta.",
	checked: "Consultado",
	observed: "Fuente actualizada",
	source: "Revisión del portfolio indexada",
	corpus: "Corpus",
	indexed: "Indexado",
	emptyTraces:
		"No hay trazas muestreadas en esta consulta. Esto no significa que no haya solicitudes.",
	fixture: "Datos sintéticos de prueba · no son telemetría de producción",
	stages: "Etapas",
	duration: "Duración",
	outcome: "Resultado",
	ready: "Disponible",
	degraded: "Degradado",
	unavailable: "No disponible",
	fresh: "Actualizado",
	updating: "Actualizando",
	stale: "Desactualizado",
	languageStage: "Idioma",
	vector_retrieval: "Búsqueda vectorial",
	graph_retrieval: "Búsqueda en grafo",
	generation: "Generación",
	finalization: "Finalización",
};
export const operationsCopy = { en, es };
export type OperationsLocale = keyof typeof operationsCopy;
