export type AuthLocale = "en" | "es";
const english = {
	title: "Assistant backoffice",
	intro: "Private operational access. Sign in with your invited account.",
	google: "Continue with Google",
	github: "Continue with GitHub",
	connecting: "Connecting to your sign-in provider…",
	signInError: "Sign-in could not start. Please try again.",
	denied:
		"This account could not be admitted. Use your invited, verified account or contact the owner.",
	unavailable: "Sign-in is temporarily unavailable. Please try again later.",
	signOut: "Sign out",
	signOutError: "Could not sign out. Try again.",
	back: "Back to overview",
	access: "Access management",
	guestEmail: "Guest email",
	invite: "Invite viewer",
	inviting: "Creating invitation…",
	invalidEmail: "Enter a valid email address.",
	inviteError: "The invitation could not be created. Try again.",
	share:
		"Share this one-use link privately. It expires in 48 hours and requires the invited account.",
	inviteLink: "Invitation link",
	copy: "Copy link",
	copied: "Copied.",
	copyFallback: "Select the link to copy it manually if needed.",
	members: "Members",
	invitations: "Invitations",
	owner: "Owner",
	viewer: "Viewer",
	revoked: "Revoked",
	used: "Used",
	expired: "Expired",
	pending: "Pending",
	revoke: "Revoke",
	revokeTitle: "Revoke access?",
	revokeMember:
		"This viewer will lose access immediately and their sessions will end.",
	revokeInvitation: "This invitation will no longer admit its recipient.",
	confirmRevoke: "Confirm revocation",
	cancel: "Cancel",
	revoking: "Revoking…",
	revokeError: "Access could not be revoked. Please try again.",
	linkTitle: "Link another sign-in account",
	linkIntro: "Link only accounts you own. Your current session is required.",
	linkGoogle: "Link Google",
	linkGithub: "Link GitHub",
	linkError: "The account could not be linked. Please try again.",
	language: "Language",
	english: "English",
	spanish: "Español",
};
type AuthCopy = { [Key in keyof typeof english]: string };
const spanish: AuthCopy = {
	title: "Panel de administración del asistente",
	intro: "Acceso privado a la operación. Inicia sesión con tu cuenta invitada.",
	google: "Continuar con Google",
	github: "Continuar con GitHub",
	connecting: "Conectando con el proveedor de acceso…",
	signInError: "No se pudo iniciar el acceso. Inténtalo de nuevo.",
	denied:
		"Esta cuenta no pudo acceder. Usa tu cuenta invitada y verificada o contacta al propietario.",
	unavailable:
		"El acceso no está disponible por el momento. Inténtalo más tarde.",
	signOut: "Cerrar sesión",
	signOutError: "No se pudo cerrar la sesión. Inténtalo de nuevo.",
	back: "Volver al resumen",
	access: "Administración de accesos",
	guestEmail: "Correo de la persona invitada",
	invite: "Invitar a un lector",
	inviting: "Creando la invitación…",
	invalidEmail: "Ingresa un correo válido.",
	inviteError: "No se pudo crear la invitación. Inténtalo de nuevo.",
	share:
		"Comparte este enlace de un solo uso en privado. Vence en 48 horas y requiere la cuenta invitada.",
	inviteLink: "Enlace de invitación",
	copy: "Copiar enlace",
	copied: "Copiado.",
	copyFallback:
		"Selecciona el enlace para copiarlo manualmente si lo necesitas.",
	members: "Miembros",
	invitations: "Invitaciones",
	owner: "Propietario",
	viewer: "Lector",
	revoked: "Revocado",
	used: "Usada",
	expired: "Vencida",
	pending: "Pendiente",
	revoke: "Revocar",
	revokeTitle: "¿Revocar el acceso?",
	revokeMember:
		"Esta persona perderá el acceso de inmediato y sus sesiones finalizarán.",
	revokeInvitation:
		"Esta invitación ya no permitirá el acceso de su destinatario.",
	confirmRevoke: "Confirmar revocación",
	cancel: "Cancelar",
	revoking: "Revocando…",
	revokeError: "No se pudo revocar el acceso. Inténtalo de nuevo.",
	linkTitle: "Vincular otra cuenta de acceso",
	linkIntro:
		"Vincula solo cuentas que te pertenezcan. Necesitas una sesión activa.",
	linkGoogle: "Vincular Google",
	linkGithub: "Vincular GitHub",
	linkError: "No se pudo vincular la cuenta. Inténtalo de nuevo.",
	language: "Idioma",
	english: "English",
	spanish: "Español",
};
export const authCopy: Record<AuthLocale, AuthCopy> = {
	en: english,
	es: spanish,
};
export function authLocale(value: unknown): AuthLocale {
	return value === "es" ? "es" : "en";
}
